# System utilities
SYSTEM_UTILS=(
  nvidia-prime
  flatpak
  file-roller
  7zip
  unrar
  unzip
  nwg-look
  btop
  nvtop
  pulsemixer
  xdg-desktop-portal-gtk
  xdg-desktop-portal-hyprland
  gnome-keyring
  brightnessctl
  polkit-gnome
  wl-clipboard
  mpd-mpris
  inotify-tools
  rsync
  syncthing
)

# Development tools
DEV_TOOLS=(
  kitty
  zsh
  fzf
  ripgrep
  fd
  zoxide
  fastfetch
  vim
  neovim
  git
  eza
  man-db
  starship
  npm
  dotnet-sdk
  opencode
  tree
  github-cli
  tree-sitter-cli
  code
  typst
  wget
)

# System maintenance
MAINTENANCE=(
  ncdu
  powertop
)

# Desktop environment
DESKTOP=(
  hyprland
  materia-gtk-theme
  bibata-cursor-theme-bin
  rofi
  nautilus
  ncspot
  dunst
  grim
  slurp
  ly
  stow
  blueman
)

# Media packages
MEDIA=(
  mpv
  zen-browser-bin
  qbittorrent
  steam
  heroic-games-launcher-bin
  celluloid
  loupe
  sptlrx-bin
  proton-vpn-cli
  obs-studio
  yt-dlp
  zathura
  zathura-pdf-mupdf
  feishin-bin
  mangohud
)

# Fonts
FONTS=(
  ttf-jetbrains-mono-nerd
  noto-fonts-emoji
  otf-ipaexfont
)

GAME_DEV=(
  unityhub
  blender
  reaper
  reapack
  sws
)


STOW=(
  dunst
  hypr
  kitty
  mpv
  nvim
  rofi
  starship
  userdirs
  zsh
)
