# System utilities
SYSTEM_UTILS=(
  file-roller
  7zip
  unrar
  unzip
  nwg-look
  btop
  nvtop
  pulsemixer
  xdg-desktop-portal-gtk
  xdg-desktop-portal-hyprland
  brightnessctl
  wl-clipboard
  hyprpolkitagent
  rsync
  cliphist
  egl-wayland
  libva-nvidia-driver
  nvidia-open-dkms
  nvidia-utils
  udiskie
  linux-headers
  nvidia-prime
  libva-utils
)

# Development tools
DEV_TOOLS=(
  kitty
  zsh
  fzf
  ripgrep
  fd
  zoxide
  fastfetch
  vim
  neovim
  git
  eza
  starship
  npm
  tree
  github-cli
  tree-sitter-cli
  typst
  wget
  tailscale
  syncthing
  python-rich
  python-prompt_toolkit
)

# System maintenance
MAINTENANCE=(
  ncdu
  powertop
  tlp
)

# Desktop environment
DESKTOP=(
  hyprland
  materia-gtk-theme
  waypaper
  yazi
  nautilus
  dunst
  grim
  slurp
  ly
  stow
  bluetui
  impala
  fuzzel
  awww
  tty-clock
)

# Media packages 
MEDIA=(
  mpv
  zen-browser-bin
  obsidian
  qbittorrent
  steam
  heroic-games-launcher-bin
  prismlauncher
  ncspot
  celluloid
  loupe
  proton-vpn-cli
  obs-studio
  yt-dlp
  zathura
  zathura-pdf-mupdf
  mangohud
  caligula
)

# Fonts
FONTS=(
  ttf-jetbrains-mono-nerd
  noto-fonts
  noto-fonts-emoji
  otf-ipaexfont
)

GAME_DEV=(
  blender
  godot
  gimp
  krita
)


STOW=(
  dunst
  fuzzel
  hypr
  kitty
  mpv
  nvim
  starship
  userdirs
  zsh
  ly
)
