# System utilities
SYSTEM_UTILS=(
  nvidia-prime
  flatpak
  file-roller
  7zip
  unrar
  unzip
  nwg-look
  btop
  pulsemixer
  xdg-desktop-portal-gtk
  gnome-keyring
  brightnessctl
  polkit-gnome
  wl-clipboard
)

# Development tools
DEV_TOOLS=(
  kitty
  zsh
  fzf
  ripgrep
  fd
  zoxide
  fastfetch
  vim
  neovim
  git
  eza
  man
  starship
  npm
  dotnet-sdk
  opencode
  tree
)

# System maintenance
MAINTENANCE=(
  ncdu
  powertop
)

# Desktop environment
DESKTOP=(
  hyprland
  materia-gtk-theme
  bibata-cursor-theme-bin
  rofi
  nautilus
  ncspot
  dunst
  grim
  slurp
  ly
  stow
)

# Media packages
MEDIA=(
  mpv
  zen-browser-bin
  qbittorrent
  steam
  heroic-games-launcher-bin
  celluloid
  loupe
  sptlrx-bin
  proton-vpn-cli
)

# Fonts
FONTS=(
  ttf-jetbrains-mono-nerd
  noto-fonts-emoji
  otf-ipaexfont
)

GAME_DEV=(
  unityhub
)


STOW=(
  dunst
  hypr
  kitty
  mpv
  nvim
  rofi
  starship
  userdirs
  zsh
)
