# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
window_padding_width 5
tab_bar_style slant
enable_audio_bell no
notify_on_cmd_finish unfocused
cursor_trail 1

background            #0e0e0e
foreground            #a4a1a1
cursor                #a4a1a1
selection_background  #494542
selection_foreground  #0e0e0e

# black
color0   #090200
color8   #5b5754
# red
color1   #c4513a
color9   #d4836a
# green
color2   #7a9f5a
color10  #3a3332
# yellow
color3   #c9a84c
color11  #494542
# blue
color4   #6a8fa8
color12  #7f7c7b
# magenta
color5   #9e7a8a
color13  #d6d4d3
# cyan
color6   #9ab8b8
color14  #b89a5a
# white
color7   #a4a1a1
color15  #e8e6e4
