foreground         #c8c8c3
background         #24240f
background_opacity 1.0
cursor             #c8c8c3

active_tab_foreground     #24240f
active_tab_background     #c8c8c3
inactive_tab_foreground   #c8c8c3
inactive_tab_background   #24240f

active_border_color   #c8c8c3
inactive_border_color #24240f
bell_border_color     #635c3a

color0       #24240f
color8       #74745e
color1       #635c3a
color9       #857B4E
color2       #5c624e
color10      #7B8369
color3       #7b6e2c
color11      #A5933B
color4       #736f49
color12      #9A9462
color5       #5a666a
color13      #78898E
color6       #7c7f75
color14      #A6AA9D
color7       #9c9c92
color15      #c8c8c3
