foreground         #c7c4c2
background         #20160e
background_opacity 1.0
cursor             #c7c4c2

active_tab_foreground     #20160e
active_tab_background     #c7c4c2
inactive_tab_foreground   #c7c4c2
inactive_tab_background   #20160e

active_border_color   #c7c4c2
inactive_border_color #20160e
bell_border_color     #6b4b25

color0       #20160e
color8       #72665d
color1       #6b4b25
color9       #8F6532
color2       #5d625b
color10      #7C837A
color3       #6f6954
color11      #948C70
color4       #997d4e
color12      #CCA769
color5       #345867
color13      #46768A
color6       #4e6e78
color14      #6993A0
color7       #9b9690
color15      #c7c4c2
