foreground         #c7c6c3
background         #221c10
background_opacity 1.0
cursor             #c7c6c3

active_tab_foreground     #221c10
active_tab_background     #c7c6c3
inactive_tab_foreground   #c7c6c3
inactive_tab_background   #221c10

active_border_color   #c7c6c3
inactive_border_color #221c10
bell_border_color     #4b443b

color0       #221c10
color8       #736c5e
color1       #4b443b
color9       #645B4F
color2       #544d41
color10      #706757
color3       #5b544b
color11      #7A7164
color4       #635a4b
color12      #857964
color5       #5d6057
color13      #7D8075
color6       #746952
color14      #9B8D6E
color7       #9c9891
color15      #c7c6c3
