general {
    gaps_in = 4
    gaps_out = 10
    border_size = 0
    resize_on_border = true
    allow_tearing = false
    layout = dwindle # master, dwindle, scrolling
}

decoration {
    rounding = 6
    active_opacity = 1
    inactive_opacity = 1
}

dwindle {
    pseudotile = true
    preserve_split = true
}

