foreground         #c6c3c3
background         #1b100f
background_opacity 1.0
cursor             #c6c3c3

active_tab_foreground     #1b100f
active_tab_background     #c6c3c3
inactive_tab_foreground   #c6c3c3
inactive_tab_background   #1b100f

active_border_color   #c6c3c3
inactive_border_color #1b100f
bell_border_color     #485027

color0       #1b100f
color8       #705c5c
color1       #485027
color9       #616B34
color2       #4c3c39
color10      #66504D
color3       #7c393a
color11      #A64D4E
color4       #724947
color12      #99625F
color5       #816c54
color13      #AC9171
color6       #755369
color14      #9C6F8D
color7       #9a9090
color15      #c6c3c3
