networks:
  arrnet:
    name: arrnet
    ipam:
      config:
        - subnet: 172.39.0.0/24

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      arrnet:
        ipv4_address: 172.39.0.2
    ports:
      - 8080:8080 #qbittorrent
      - 6881:6881 #qbittorrent
      - 6881:6881/udp #qbittorrent
      - 6789:6789 #nzbget
      - 9696:9696 #prowlarr
    volumes:
      - /data/config/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=COEG8rwk4bUCxzLOuUn1wcri6in/J6Vp0JZOm0KaKVs=
      - SERVER_COUNTRIES=Netherlands
      - BLOCK_MALICIOUS=off # Disable unbound DNS resolver
      - HEALTH_VPN_DURATION_INITIAL=120s

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/config/nzbget:/config
      - /data:/data
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/config/qbittorrent:/config
      - /data:/data
    restart: unless-stopped
 
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/config/jellyfin:/config
      - /data:/data
    networks:
      arrnet:
        ipv4_address: 172.39.0.10
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1001
      - LOG_LEVEL=info
      - TZ=Etc/UTC
      - PORT=5055 #optional
    networks:
      arrnet:
        ipv4_address: 172.39.0.11
    ports:
      - 5055:5055
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/config/jellyseerr:/app/config
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
    networks:
      arrnet:
        ipv4_address: 172.39.0.4
    ports:
      - 7878:7878 #radarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/config/radarr:/config
      - /data:/data
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
    networks:
      arrnet:
        ipv4_address: 172.39.0.3
    ports:
      - 8989:8989 #sonarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/config/sonarr:/config
      - /data:/data
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
    network_mode: "service:gluetun"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/config/prowlarr:/config
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
    networks:
      arrnet:
        ipv4_address: 172.39.0.6
    ports:
      - 6767:6767 #bazarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/config/bazarr:/config
      - /data:/data
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
    networks:
      arrnet:
        ipv4_address: 172.39.0.5
    ports:
      - 8686:8686 #lidarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/config/lidarr:/config
      - /data:/data
    restart: unless-stopped

